### ISSUE TITLE
GetMessage name conflict

### ISSUE THREAD

**Issue by bstriner** [protocolbuffers/protobuf#5051]
**What version of protobuf and what language are you using?**
Version: master
Language: C++/Python

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
VC

**What did you do?**
`winuser.h` defines `GetMessage` as `GetMessageA` or `GetMessageW`. `Reflection::GetMessage` is declared in `message.h` and `GeneratedMessageReflection::GetMessage` is declared in `generated_message_reflection.h`.

If you include headers in the order `message.h`, `winuser.h`, `generated_message_reflection.h` you get the following error:

```
error C3668: 'google::protobuf::internal::GeneratedMessageReflection::GetMessageA': method with override specifier 'override' did not override any base class methods
```

This happens a few places when building tensorflow on windows. If `windows.h` is going to be included, make sure it is before anything from protobuf.

Seems like two directions would be to either always include windows.h, or to always undef GetMessage.

**Comment by xfxyjwf** [comment]
Can you help check what version introduced this error? I don't remember seeing such errors before. Is it only in master? Have you tried version 3.6.1?

**Comment by xfxyjwf** [comment]
This should be resolved by the latest master.

**Comment by bstriner** [comment]
@xfxyjwf sorry lost track of this. I think it is still happening but I'll check when I get a chance. Stable TF build still waiting on protobuf release for other reasons. 3.6.1 is missing some updates for python 3.7 so I can't reproduce exactly in 3.6.1.

I used this patch to build, which just adds `#undef GetMessage` in two places.

https://gist.github.com/bstriner/1d4ee0db5e5efcc04c6a82b20ee0bebb

Some related discussion: https://github.com/tensorflow/tensorflow/pull/21202

Cheers

**Comment by bstriner** [comment]
Also, a weird interaction I'm not sure the source of. TF build with protobuf master fails on finding skylib unless you copy the skylib definition from the protobuf workspace to the TF workspace. The TF build didn't change so must be something with a change to the protobuf build. Something wonky with the way TF includes protobuf includes skylib. See last comment in that thread.

Workaround is easy but I'm still intrigued by the cause.

**Comment by bstriner** [comment]
@xfxyjwf Yup! Just confirmed this build works on current master. This issue still happening though: https://github.com/protocolbuffers/protobuf/issues/5178
