### ISSUE TITLE
[Java] Merge of oneof type - ClassCastException

### ISSUE THREAD

**Issue by Dimezis** [protocolbuffers/protobuf#7915]
**What version of protobuf and what language are you using?**
Version: 3.13.0, (with Lite option on)
Language: Java

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
AdoptOpenJDK 14, com.google.protobuf 3.13.0 gradle plugin

**What did you do?**
Consider the following oneof type (Proto 3).

```
message Status {
    oneof status {
        bool ok = 1;
        Error error = 2;
    }

    message Error {
        string reason = 1;
    }
}
```

and then merge 2 messages of this type, with different oneof cases:

```
val ok = Status.newBuilder().setOk(true).build()
val error = Status.newBuilder()
        .setError(
            Status.Error.newBuilder()
                .setReason("reason")
                .build()
        ).build()

val result = ok.toBuilder().mergeFrom(error)
assert(result.equals(error))
```

**What did you expect to see**
I expected the `error` to override `ok` oneof case in `result` message, so the `result` will contain `error` message, since oneof cases are mutually exclusive.
However, I can't find any rules of merging oneof fields in the documentation, so my expectation might be wrong.

**What did you see instead?**
Crash in mergeFrom method:
```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to com.google.protobuf.MessageLite
	at com.google.protobuf.Internal.mergeMessage(Internal.java:387)
	at com.google.protobuf.MessageSchema.mergeOneofMessage(MessageSchema.java:1409)
	at com.google.protobuf.MessageSchema.mergeSingleField(MessageSchema.java:1355)
	at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:1184)
	at com.google.protobuf.GeneratedMessageLite$Builder.mergeFromInstance(GeneratedMessageLite.java:423)
	at com.google.protobuf.GeneratedMessageLite$Builder.mergeFrom(GeneratedMessageLite.java:418)
```

**Comment by Dimezis** [comment]
Can anyone confirm if it's a bug?

**Comment by demeero** [comment]
Don't know what's going on in Java implementation, but with Go, your case works fine.
```
statusOK := &pb.Status{
		Status: &pb.Status_Ok{Ok: true},
	}
	statusErr := &pb.Status{
		Status: &pb.Status_Error_{Error: &pb.Status_Error{Reason: "some reason"}},
	}
	fmt.Printf("before merge - statusOK.GetError().GetReason()=%v,statusOK.GetStatus()=%v\n",
		statusOK.GetError().GetReason(), statusOK.GetStatus())
	proto.Merge(statusOK, statusErr)
	fmt.Printf("after merge - statusOK.GetError().GetReason()=%v,statusOK.GetStatus()=%v",
		statusOK.GetError().GetReason(), statusOK.GetStatus())
```

Output:

```
before merge - statusOK.GetError().GetReason()=,statusOK.GetStatus()=&{true}

after merge - statusOK.GetError().GetReason()=some reason,statusOK.GetStatus()=&{reason:"some reason" }

```

**Comment by Dimezis** [comment]
Which confirms my expectations. 
So seems like merge implementation in Java needs a fix

**Comment by acozzette** [comment]
@Dimezis Thank you for the bug report. I believe this has been fixed in #7698 but the fix has not made it into a release yet.

**Comment by Dimezis** [comment]
@acozzette I haven't tested the changes in that PR, but just after briefly reviewing the code, I don't think it covers the case I described here

**Comment by acozzette** [comment]
I could be wrong but it looked to me like this test case covered the same bug reported on this issue: https://github.com/protocolbuffers/protobuf/blob/b774da0d4255e56b957e78115cde7d4e3112af03/java/lite/src/test/java/com/google/protobuf/LiteTest.java#L1358

**Comment by Dimezis** [comment]
It seems similar, but in that test both oneof cases are of type `MessageLite`, with int field inside, whereas in my case I have one case of type `MessageLite`, and other of type bool (or other primitive). 
And I think the problem here that `mergeOf` always tries to cast the field to `MessageLite` in such cases.

**Comment by Dimezis** [comment]
I'm not able to build the protoc on macos, so could you confirm that it's still happening on master?

**Comment by Dimezis** [comment]
I have tested the same code snipped I posted above on `3.14.0` and can confirm it's working
