### ISSUE TITLE
C#: Increase recursionLimit for MessageParser

### ISSUE THREAD

**Issue by mikhailshilkov** [protocolbuffers/protobuf#7995]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
No way to set `recursionLimit` via `MessageParser`.

gRPC library for .NET has [this issue](https://github.com/grpc/grpc/issues/22682) where it fails to parse a message with high recursion. However, there's seemingly no hook to configure a `MessageParser` (the entry point that the generated gRPC code uses) to increase the default recursion limit from 100 to an arbitrary value.

**Describe the solution you'd like**
Have a configuration value to set a recursion limit to a higher value, either on a `MessageParser` level or globally.

**Describe alternatives you've considered**
-

**Additional context**
Downstream issue: https://github.com/pulumi/pulumi/issues/4224

**Comment by gitfool** [comment]
This is a problem in particular for Kubernetes resources which have many nested elements when represented as yaml, combined with using unstructured data via [Google.Protobuf.WellKnownTypes.Struct](https://github.com/protocolbuffers/protobuf/blob/c5f7b4b0b32baab4396d6c023dd4d74d593a0e2f/csharp/src/Google.Protobuf/WellKnownTypes/Struct.cs#L80), which effectively reduces the recursion limit by a factor of 3x.

A much needed quick fix could be to simply increase the default recursion limit to account for this, from 100 to 300 or more, and a long term configurable limit could be devised after said quick fix is released.

**Comment by jtattermusch** [comment]
I think the right solution would be to provide a hook for configuring the marshallers in gRPC. Increasing the limit globally for everyone doesn't sound like a good solution.

**Comment by jtattermusch** [comment]
I filed https://github.com/grpc/grpc/issues/24633 to address the root cause of this and I'm going to close this issue as changing the default recursion limit doesn't really solve the problem (as different projects will need different recursion limits).
