### ISSUE TITLE
PHP Package and PHP extension has different behavior when passing null message property which expects string

### ISSUE THREAD

**Issue by asdpew** [protocolbuffers/protobuf#9350]
**What version of protobuf and what language are you using?**
Version: all version
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
All Version
**What runtime / compiler are you using (e.g., python version or gcc version)**
All runtimes
**What did you do?**
When passing null to message property which expect string get error invalid value passed but when using package there are no such error.

For example 
```
message TestProtobuf{
      string random_property = 1; 
}
```

With package 
```
$test = new TestProtobuf();
$test->setRandomProperty(null);
```
no errors but with extensions
```
$test = new TestProtobuf();
$test->setRandomProperty(null);
```
exception.

I managed to track to [part](https://github.com/protocolbuffers/protobuf/blob/01e84b129361913e5613464c857734fcfe095367/php/ext/google/protobuf/convert.c#L339) it looks like it doesn't have case for `NULL`

**Comment by haberman** [comment]
The C extension and the pure-PHP library should have the same behavior. Cases where the behavior differs should be fixed.

In this case, we would have to decide whether we should allow `NULL` or not.  I would lean towards not allowing it here.

**Comment by rempet** [comment]
if we don't allow NULL how should we handle when not all message property are set? IMO we should allow NULL

**Comment by haberman** [comment]
> if we don't allow NULL how should we handle when not all message property are set? 

I don't follow.

1. You can always write `$test->setRandomProperty("")`.
2. We could consider supporting `$test->clearRandomProperty()`, which we will definitely want if we support proto2.

**Comment by deannagarcia** [comment]
Closing due to no response, feel free to reopen with more details if you're still seeing this.

**Comment by sp-joseluis-cerrada** [comment]
Hi! Sorry for opening this again, but the error still happens. The problem is that if you come from using the package, switching to the php extension may break your code, because yo might be setting some property to null and the package will work ok but the extension will throw an error.

For example:

Given this message:
```
message TestProtobuf{
      string random_property = 1; 
}
```

And given this piece of code:

```
$test = new TestProtobuf();
$test->setRandomProperty(null);
```

**With the package**

This will result in `$test->random_property` being set to `''` (empty string) due to `GPBUtil::checkString` function casting its value to the [string default value](https://github.com/protocolbuffers/protobuf/blob/01e84b129361913e5613464c857734fcfe095367/php/src/Google/Protobuf/Internal/GPBUtil.php#L98C9-L100C10)
![image](https://github.com/user-attachments/assets/c98947fa-b0bc-4d2e-bdeb-63289a490bbb)


**Now with the extension**

The same piece of code will result in an error because of [this](https://github.com/protocolbuffers/protobuf/blob/01e84b129361913e5613464c857734fcfe095367/php/ext/google/protobuf/convert.c#L50C3-L51C70)
![image](https://github.com/user-attachments/assets/6de8bede-8b37-4d4e-8102-67fda3e09b52)
